### PR TITLE
Updated Vijnana Logo

### PR DESCRIPTION
**Pull request by yadhukrishnx**
50% of logo size reduced ..Thank you :) (Ghost purushu here)

### CODE REVIEW

**Comment by aswanthabam** [comment]
Logo cannot be changed, Here is what you can do:

- submit this logo in logo design call of vijnana
- get approval from chako mash

: ) Thanks

**Comment by yadhukrishnx** [comment]
Evide njn parayumbo pakal and ratri ... No chacko mash  .  Aduthe pull name mattitt verum

**Comment by aswanthabam** [comment]
Logo looks good, send it to : kbmgclogodesign2023@gmail.com

**Comment by aswanthabam** [comment]
> Evide njn parayumbo pakal and ratri ... No chacko mash  .  Aduthe pull name mattitt verum 

Work on some major issues to get merge 🗿

**Pull request closed without merging**
